### ISSUE TITLE
CDU Input Error for A-10C ||

### ISSUE THREAD

**Issue by ocgadmin** [aronCiucu/DCSTheWay#149]
All aircraft so far work ok. except for A-10C 2. always get CDU input error when transferring to aircraft

**Comment by aronCiucu** [comment]
Hello, could you attach a video so i can take a look?

**Comment by ocgadmin** [comment]
Cheers
Will do I'm away until Sunday night


⁣Get BlueMail for Android ​

**Comment by ocgadmin** [comment]
Link to video as requested

https://drive.google.com/file/d/14AQ9evjf-gO0eGixNOsyQ4CxcXAZN1iH/view?usp=sharing

**Comment by aronCiucu** [comment]
Could you try the same in a Instant Action hot started mission? Without touching any of the CDU stuff beforehand

**Comment by ocgadmin** [comment]
Works perfectly

**Comment by ocgadmin** [comment]
This mission gives the error. Not sure why

[Pretense_syria_m_1.6r.zip](https://github.com/aronCiucu/DCSTheWay/files/14075492/Pretense_syria_m_1.6r.zip)

**Comment by aronCiucu** [comment]
The CDU input error is most likely due to the mission doing some CDU setup via scripting, I can see some messages in your video where it says something about that. Unfortunately I am not sure how to fix that issue since it's unknown what kind of setup that mission does. However the crash on exiting the game is a known issue and it will.be fixed (it only happens on mission exit though so it shouldn't impact gameplay as much).

**Comment by ocgadmin** [comment]
Thanks for looking at the problem. I've tested again and after getting the CDU error I pressed CLR and it inputs the data as "point1" 
Only does it once then back to the CDU error
This only happens on a fresh start aircraft role and The Way.

**Comment by aronCiucu** [comment]
I see, unfortunately I am not an A10 expert to know what kind of CDU setup causes this, I assume something on that server is different than the usual hot started missions, since there are many variables at play, I am not sure how to fix this in your mission.
