### ISSUE TITLE
Multimonitor support

### ISSUE THREAD

**Issue by ToastyBanK3nobi** [aronCiucu/DCSTheWay#66]
Hey @aronCiucu,

as discussed in our Discord PM here is the Issue with Multimonitor Support. Apperently the Way gets the right Coords but is shown only on the leftmost Monitor, even though it takes the Coords from the Middle one. You can´t get the Program to start on an other Monitor then the leftmost one. Screens for explanation:

![image](https://user-images.githubusercontent.com/131154255/232780173-3b4bc66a-4c6a-4c7f-8e53-e058e9f084fe.png)
![image](https://user-images.githubusercontent.com/131154255/232780224-323baf49-c208-4441-9142-262bc64c0c15.png)

Have a Good ONE, Mate!

edit: typo

**Comment by ValokAsura** [comment]
Same issue for me. Perhaps a simple fix would be to have The Way read Saved Games\DCS.openbeta\Config\appSettings.lua? For my setup, the top of the file reads as follows: 

`windowPlacement = {
    ["y"] = 0,
    ["x"] = 2560,
    ["w"] = 1920,
    ["h"] = 1080,
}`

Maybe by using this (assuming there aren't other variables I'm unaware of), The Way could know that the DCS window is 1920x1080 and is 2560 pixels offset to the right, and it can offset the green circle accordingly.

I have a 4-monitor setup with the following layout/resolutions: 1: 1080, 2: 1440, 3: 1440, 4: 1080. When I play DCS, I set monitor 3 as my primary monitor in Windows and I have DCS load full screen on monitor 4. The Way's green targeting circle loads on the primary monitor (3), so I can't select coordinates with it. Because I use the ScratchPad script for DCS I can use its targeting dot to help select coordinates for The Way.

**Comment by aronCiucu** [comment]
This will be fixed in the next version, the crosshair will always show on your DCS screen
