### ISSUE TITLE
CONFIRM BEFORE PASTE

### ISSUE THREAD

**Issue by FotiosZafeiriou** [aronCiucu/DCSTheWay#75]
Hi Team,

FA18 here VR user. 

I copy a coordinate successfully, I am in precise I am in the 00"00"0000 format. 

But it says You are not in the TAC menu 3, thus I need to confirm. 

Is there a way to fix this so we dont need to ALT TAB remove the VR and hit the Confirm dialog so we can paste the coordinate ?

Please help thank you

**Comment by aronCiucu** [comment]
Hi, unfortunately there is no way for the program to know if you have those DDIs set up the proper way for transfer, this is why you need to confirm every time. But the VR concerns are valid

**Comment by FotiosZafeiriou** [comment]
@aronCiucu 
Can I remove this statement and re-compile ?
```
    } else if (moduleRef.current === "FA-18C_hornet") {
      //show warning dialog
      AlertDialog({
        title: "Please make sure that",
        content:
          "1. PRECISE option is boxed in HSI > DATA\n" +
          "2. You are not in the TAC menu\n" +
          "3. You are in the 00°00.0000' coordinate format",
```

**Comment by FotiosZafeiriou** [comment]
@aronCiucu Which is the TAC menu ?

**Comment by aronCiucu** [comment]
You cam definitely remove parts of the code and follow to build instructions to recompile. The TAC menu is a DDI page on the Hornet.

**Comment by FalcoGer** [comment]
I'm sure you can make sure that you open the correct page. for example you could press the bottom middle button to bring either the TAC or Support page up (if TAC is open already), then press middle right for HSI or SA, depending on which page it is, and then press the bottom middle button again, because this time you can be certain that it's the TAC page. This would require a few more button presses, but would stop requiring the user to confirm every time.
